###### This file is automatically generated by CMake.
## see macro icub_app defined in conf/iCubHelpers.cmake

execute_process(COMMAND "${CMAKE_COMMAND}" -E make_directory "")
execute_process(COMMAND "${CMAKE_COMMAND}" -E make_directory "/app")
execute_process(COMMAND "${CMAKE_COMMAND}" -E make_directory "/app/behaviorManager/conf")

set(files "/home/kadir/interconnection/workspace/metu-ros-pkg/stacks/aff_learning/humanoid_aff_learning/icub_aff_learning/behavior_manager/conf/config.ini;/home/kadir/interconnection/workspace/metu-ros-pkg/stacks/aff_learning/humanoid_aff_learning/icub_aff_learning/behavior_manager/conf/grasp_model.ini;/home/kadir/interconnection/workspace/metu-ros-pkg/stacks/aff_learning/humanoid_aff_learning/icub_aff_learning/behavior_manager/conf/hand_sequences.ini")
foreach(f ${files})
	get_filename_component(fname "${f}" NAME)
	if (NOT IS_DIRECTORY "${f}")
		if (NOT EXISTS "/app/behaviorManager/conf/${fname}")
			execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${f}" "/app/behaviorManager/conf")
		else()
			execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${f}" "/app/behaviorManager/conf/${fname}" RESULT_VARIABLE test_not_successful OUTPUT_QUIET ERROR_QUIET)
			if ( test_not_successful )
				message("Preserving locally modified file: /app/behaviorManager/conf/${fname}")
				message("--> saving new file to: /app/behaviorManager/conf/${fname}.new")
				execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${f}" "/app/behaviorManager/conf/${fname}.new")
			endif()
		endif()
	endif()
endforeach(f "${files}")

