(cl:defpackage feature_factory-srv
  (:use )
  (:export
   "FEATURECALCULATION"
   "<FEATURECALCULATION-REQUEST>"
   "FEATURECALCULATION-REQUEST"
   "<FEATURECALCULATION-RESPONSE>"
   "FEATURECALCULATION-RESPONSE"
  ))

