"""autogenerated by genmsg_py from ModuleStates.msg. Do not edit."""
import roslib.message
import struct


class ModuleStates(roslib.message.Message):
  _md5sum = "5db198112592b255720236133b837d16"
  _type = "aff_msgs/ModuleStates"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# This message is sent to all of the nodes to synchronize sensori-data acquisition,
# action, observation and teleoperation stuff.

bool workspace_detector
bool behavior_manager

"""
  __slots__ = ['workspace_detector','behavior_manager']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       workspace_detector,behavior_manager
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(ModuleStates, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.workspace_detector is None:
        self.workspace_detector = False
      if self.behavior_manager is None:
        self.behavior_manager = False
    else:
      self.workspace_detector = False
      self.behavior_manager = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.workspace_detector, _x.behavior_manager))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.workspace_detector, _x.behavior_manager,) = _struct_2B.unpack(str[start:end])
      self.workspace_detector = bool(self.workspace_detector)
      self.behavior_manager = bool(self.behavior_manager)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.workspace_detector, _x.behavior_manager))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.workspace_detector, _x.behavior_manager,) = _struct_2B.unpack(str[start:end])
      self.workspace_detector = bool(self.workspace_detector)
      self.behavior_manager = bool(self.behavior_manager)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2B = struct.Struct("<2B")
