uint8 DO_PERCEPT = 0
uint8 EXTRACT_EFFECT = 1
uint8 task
int8 arg
---
#uint8 PROCESSING = 0
uint8 DONE = 1
uint8 feedback
#sensor_msgs/PointCloud2 pushable_object
float32[] pushable_object_center
float32[] pushable_object_size
