"""autogenerated by genmsg_py from PerceiveRangeData.msg. Do not edit."""
import roslib.message
import struct


class PerceiveRangeData(roslib.message.Message):
  _md5sum = "8addac4e4f12ab38392d4ae360422b58"
  _type = "affordances_msgs/PerceiveRangeData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool do_perceive

"""
  __slots__ = ['do_perceive']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       do_perceive
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(PerceiveRangeData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.do_perceive is None:
        self.do_perceive = False
    else:
      self.do_perceive = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      buff.write(_struct_B.pack(self.do_perceive))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 1
      (self.do_perceive,) = _struct_B.unpack(str[start:end])
      self.do_perceive = bool(self.do_perceive)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      buff.write(_struct_B.pack(self.do_perceive))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.do_perceive,) = _struct_B.unpack(str[start:end])
      self.do_perceive = bool(self.do_perceive)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_B = struct.Struct("<B")
