(cl:defpackage pr2_learning_affordances-srv
  (:use )
  (:export
   "EXECUTECARTESIANIKTRAJECTORY"
   "<EXECUTECARTESIANIKTRAJECTORY-REQUEST>"
   "EXECUTECARTESIANIKTRAJECTORY-REQUEST"
   "<EXECUTECARTESIANIKTRAJECTORY-RESPONSE>"
   "EXECUTECARTESIANIKTRAJECTORY-RESPONSE"
  ))

